[project]
name = "android-helper"
version = "2.0.0"
requires-python = ">=3.10"
description = "Android Debloat & Install Helper (multi-profile)"
readme = "README.md"

[project.scripts]
android-helper = "android_helper.cli:main"
