---
name: CI

on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint (ruff, py310)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install ruff (pinned)
        run: python -m pip install ruff==0.5.7

      - name: Ruff check
        run: python -m ruff check src android_helper.py

  smoke:
    name: Smoke test (install + CLI, py310)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package
        run: python -m pip install .

      - name: CLI help (console script)
        run: android-helper --help

      - name: Module entrypoint
        run: python -m android_helper.cli --help
